# Generated by Django 3.0.5 on 2020-04-20 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_player_name', models.CharField(max_length=100)),
                ('out_player_name', models.CharField(max_length=100)),
                ('minute', models.IntegerField()),
                ('team_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=300)),
                ('minute', models.IntegerField()),
                ('team_name', models.CharField(max_length=100)),
                ('card', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='FreeKick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shooter_name', models.CharField(max_length=100)),
                ('barrier_names', models.CharField(max_length=300)),
                ('team_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('minute', models.IntegerField()),
                ('team', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team_name', models.CharField(max_length=300)),
                ('home_team_score', models.IntegerField()),
                ('away_team_name', models.CharField(max_length=300)),
                ('away_team_score', models.IntegerField()),
                ('stadium_name', models.CharField(default=None, max_length=300)),
                ('date', models.CharField(max_length=10)),
                ('start_time', models.CharField(max_length=10)),
                ('change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.Change')),
                ('fault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.Fault')),
                ('free_kick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.FreeKick')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.Goal')),
            ],
        ),
    ]
