# Generated by Django 3.0.5 on 2020-04-19 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team_name', models.CharField(max_length=300)),
                ('home_team_score', models.IntegerField()),
                ('away_team_name', models.CharField(max_length=300)),
                ('away_team_score', models.IntegerField()),
                ('date', models.CharField(max_length=10)),
                ('start_date', models.CharField(max_length=10)),
            ],
        ),
    ]
