# Generated by Django 3.0.5 on 2020-04-20 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_match_stadium_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='start_date',
            new_name='start_time',
        ),
    ]
