# Generated by Django 3.0.5 on 2020-04-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('creation_year', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('sponsor', models.CharField(max_length=100)),
            ],
        ),
    ]
