# Generated by Django 3.0.5 on 2020-04-20 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('population_size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('legal_representative', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('origin_city', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='team',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.City'),
        ),
        migrations.AlterField(
            model_name='team',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Sponsor'),
        ),
    ]
